export const SET_EDITOR_STATE = 'SET_EDITOR_STATE'

export const RECEIVE_SCREENSHOT = 'RECEIVE_SCREENSHOT'
export const REMOVE_SCREENSHOT = 'REMOVE_SCREENSHOT'
export const UPDATE_SCREENSHOT = 'UPDATE_SCREENSHOT'

export const RECEIVE_TWEET_THREAD = 'RECEIVE_TWEET_THREAD'
export const SET_ACTIVE_TWEET = 'SET_ACTIVE_TWEET'

export const SET_AUTOCOMPLETE_TERM = 'SET_AUTOCOMPLETE_TERM'
export const SET_AUTOCOMPLETE_LIST = 'SET_AUTOCOMPLETE_LIST'
export const UPDATE_AUTOCOMPLETE_INDEX = 'UPDATE_AUTOCOMPLETE_INDEX'
export const SELECT_AUTOCOMPLETE_ITEM = 'SELECT_AUTOCOMPLETE_ITEM'

export const RECEIVE_AUTHENTICATED_USER = 'RECEIVE_AUTHENTICATED_USER'
export const RECEIVE_FRIENDS = 'RECEIVE_FRIENDS'

export const ADD_TWEET = 'ADD_TWEET'
export const TWEET_SENT = 'TWEET_SENT'

export const SHOW_BANNER = 'SHOW_BANNER'
export const HIDE_BANNER = 'HIDE_BANNER'

export const START_TWEET = 'START_TWEET'
export const START_SCREENSHOT = 'START_SCREENSHOT'
export const CLOSE_APP = 'CLOSE_APP'
export const RECEIVE_ACTIVE_VIEW = 'RECEIVE_ACTIVE_VIEW'
export const SET_APP_ENABLED = 'SET_APP_ENABLED'