// UI constants
export const ACTIVE_VIEW_THREAD = 'ACTIVE_VIEW_THREAD'
export const ACTIVE_VIEW_COMPOSER = 'ACTIVE_VIEW_COMPOSER'
export const ACTIVE_VIEW_NONE = 'ACTIVE_VIEW_NONE'
export const DEFAULT_EDITOR_ID = 'DEFAULT_EDITOR_ID'

// Storage keys
export const AUTHED_USER_STORAGE_KEY = 'authenticatedUser'
export const FRIENDLIST_STORAGE_KEY = 'friends'
export const SHOT_BLACKLIST_STORAGE_KEY = 'shotButtonBlacklist'

export const RECEIVE_THREAD_KEY = 'RECEIVE_TWEET_THREAD'

export const DISPATCH_ACTION = 'DISPATCH_ACTION'

export const RUNTIME_REQUEST_SUCCESS = 'RUNTIME_REQUEST_SUCCESS'
export const RUNTIME_REQUEST_FAILURE = 'RUNTIME_REQUEST_FAILURE'
export const RUNTIME_REQUEST_RECEIVED = 'RUNTIME_REQUEST_RECEIVED'